[package]
name = "convolution_vst"
version = "0.1.1"
edition = "2021"
authors = ["Marinus Burger <marinus.burger@gmail.com>"]
license = "ISC"

[lib]
crate-type = ["cdylib", "lib"]
#name = "convolution_vst_lib"


[dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", features = ["standalone", "vst3"] }
nih_plug_vizia = { git = "https://github.com/robbert-vdh/nih-plug.git" }
parking_lot = "0.12.5"
rand = "0.8.5"
image = "0.24"

[workspace]
members = [
    "xtask",
]

[profile.dev.package."*"]
opt-level = 3
